books/urls.py
from django.urls import path
from .views import CategoryView, BookDetail,AddCommentView,about,books,GenresView

app_name = 'books'
urlpatterns = [
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('genre/<int:genre_id>/', GenresView.as_view(), name='genres'),
    path('detail/<int:pk>/', BookDetail.as_view(), name='detail'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='add_comment'),
    path('about/', about, name='about'),
    path('books/', books, name='books'),
]

mybooks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
]

templates/includes/main.html
{% load static %}
{% load mathfilters %}
<div class="main">
        <!-- content -->
        <section class="content">
            {% for book in book_page %}
            	<div class="post">
            <!-- post-inner -->
            <div class="post-inner">
              <header>
                <h2><a href="#">{{ book.name }}</a></h2>
                <p class="tags"><a href="#">{{ book.category.name }}</a> <a href="#">{{ book.genre.name }}</a> </p>
                <div class="cl">&nbsp;</div>
              </header>
              <div class="img-holder"> <a href="#"><img src="{{ book.image.url }}" alt="" width="100%"></a> <a href="{{ book.image.url }}" class="btn-full-image popup"><span>FULL IMAGE</span></a> </div>
              <!-- meta -->
              <div class="meta">
                <p class="date">{{ book.year }} by <a>{{ book.author }}</a></p>
                <div class="right">
                  <div class="rating-holder">
                    <p>REYTING</p>&nbsp;
                        {% for key,value in ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-solid fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                        {% for key,value in regular_ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}

                  </div>
                  <a href="#" class="comments">{{ book.comments.count }} ta izoh</a> </div>
                <div class="cl">&nbsp;</div>
              </div>
              <!-- end of meta -->
              <!-- post-cnt -->
              <div class="post-cnt">
                <p>{{ book.about|truncatewords:60|linebreaks }}</p>
                <a href="{% url 'books:detail' book.pk %}" class="more">Batafsil o'qish</a> </div>
              <!-- end of post-cnt -->
            </div>
            <!-- post-inner -->
          </div>
            {% endfor %}

          <div class="pagination">
            <ul>
            {% if book_page.has_previous %}
                <li class="laquo"><a href="?page={{ book_page.previous_page_number }}"><span></span></a></li>
            {% else %}
                <li class="laquo"><a><span></span></a></li>
            {% endif %}

              {% for page_num in page_nums %}
              	<li class="{% if request.GET.page == page_num|slugify %}active{% endif %}"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
              {% endfor %}
                {% if book_page.has_next %}
                    <li class="raquo"><a href="?page={{ book_page.next_page_number }}"><span></span></a></li>
                {% else %}
                  <li class="raquo"><a><span></span></a></li>
                {% endif %}
            </ul>
          </div>
        </section>
        <!-- end of content -->
        <!-- sidebar -->
        <aside class="sidebar">
          <div class="widget">
            <h3 class="widgettitle">Kategoriyalar</h3>
            <ul>
             {% for category in categories %}
             	 <li><a href="{% url 'books:category' category.id %}">{{ category.name }}</a></li>
             {% endfor %}

            </ul>
          </div>
          <div class="widget">
            <h3 class="widgettitle">Janrlar</h3>
            <ul>
              {% for genre in genres %}
              	<li><a href="{% url 'books:genres' genre.id %}">{{ genre.name }}</a></li>
              {% endfor %}

            </ul>
          </div>
          <div class="widget socials-widget">
            <h3 class="widgettitle">Ijtimoiy tarmoqlarimiz</h3>
            <ul>
              <li><a class="facebook-ico"><span></span>Facebook</a></li>
              <li><a class="twitter-ico"><span></span>Twitter</a></li>
              <li><a class="linkedin-ico"><span></span>Linkedin</a></li>
              <li><a class="you-tube-ico"><span></span>Youtube</a></li>
              <li><a class="rss-ico"><span></span>RSS</a></li>
            </ul>
          </div>
        </aside>
        <!-- end of sidebar -->
        <div class="cl">&nbsp;</div>
      </div>

<div class="modal" id="myModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Ro'yxatdan o'tish</h2>
    <form action="#" method="POST">
        {% csrf_token %}
        {{ forms }}
        <span>Allaqachon hisobingiz bormi? <span id="login" class="signup">Kirish</span></span>
      <button type="submit">Ro'yxatdan o'tish</button>
    </form>
  </div>
</div>
<div class="modal" id="loginModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Kirish</h2>
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form }}
        <span>Akkountingiz yo'qmi? <span id="myBtn" class="signup">Ro'yxatdan o'tish</span></span>
        <button type="submit">Kirish</button>
    </form>
  </div>
</div>

<script>
// Modalni ochish va yopish
var registerModal = document.getElementById("myModal");
var registerBtn = document.getElementById("myBtn");
var registerClose = registerModal.getElementsByClassName("close")[0];

registerBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "block";
    loginModal.style.display = "none";
})


registerClose.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "none";
})

var loginModal = document.getElementById("loginModal");
var loginBtn = document.getElementById("loginBtn");
var loginClose = loginModal.getElementsByClassName("close")[0];

loginBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})

loginClose.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "none";
})

var login = document.getElementById("login");

login.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})


</script>

templates/includes/navbar.html
{% load static %}
<div class="header">
        <div class="logo">
            <img width="50px" src="{% static 'mybook/css/images/logo.png' %}" alt="">
            <span>Bookinfo.uz</span>
        </div>
        <!-- navigation -->
        <nav id="navigation">
          <ul>
            <li><a href="{% url 'index' %}"><i class="fa-solid fa-house"></i> Bosh sahifa</a></li>
           <li><a href="{% url 'books:books' %}"><i class="fa-solid fa-book"></i> Kitoblar</a></li>
            <li><a href="{% url 'books:about' %}"><i class="fa-solid fa-address-card"></i> Biz haqimizda</a></li>
            {% if user.is_authenticated %}
            	<li><a href="{% url 'users:profile' %}"><i class="fa-solid fa-user"></i> {{ user.username }}</a>
                </li>
            {% else %}
                <li><a href="#" id="loginBtn"><i class="fa-solid fa-user"></i> KIRISH</a></li>
            {% endif %}
          </ul>
        </nav>
        <!-- end of navigation -->
        <div class="cl">&nbsp;</div>
      </div>