books/urls.py
from django.urls import path
from .views import CategoryView, BookDetail,AddCommentView,about,books,GenresView

app_name = 'books'
urlpatterns = [
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('genre/<int:genre_id>/', GenresView.as_view(), name='genres'),
    path('detail/<int:pk>/', BookDetail.as_view(), name='detail'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='add_comment'),
    path('about/', about, name='about'),
    path('books/', books, name='books'),
]

mybooks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='user_images/', blank=True, null=True)
    phone = models.CharField(max_length=13)

users/forms.py
from django import forms
from .models import User


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(widget=forms.EmailInput())
    password2 = forms.CharField(label="Confirm password",widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','email', 'password', 'password2', 'first_name', 'last_name')

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password2 != password:
            raise forms.ValidationError("Passwords don't match")
        return password

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 5 or len(username) > 30:
            raise forms.ValidationError("Username 5 va 30 orasida bo'lishi kerak")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Bunday email bazada mavjud")
        return email

class ProfileForm(forms.ModelForm):
    username = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control w-100'}))
    first_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={'placeholder': 'First name', 'class': 'form-control w-100'}))
    last_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={'placeholder': 'Last name', 'class': 'form-control w-100'}))
    email = forms.CharField(disabled=True ,label="", widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control w-100'}))
    image = forms.ImageField(label="", widget=forms.FileInput(attrs={'class': 'form-control'}))


    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', "email", 'image']

class ResetPasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean_confirm_password(self):
        password = self.cleaned_data.get('new_password')
        password2 = self.cleaned_data.get('confirm_password')

        if password2!=password:
            raise forms.ValidationError("Passwords don't match")
        return password

users/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect,render
from .forms import ProfileForm, ResetPasswordForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


def logout_user(request):
    logout(request)
    return redirect('index')

def profile(request):
    return render(request, 'users/profile.html')

def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST,instance=request.user, files=request.FILES)
        forms = ResetPasswordForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
        if forms.is_valid():
            old_password = forms.cleaned_data['old_password']
            new_password = forms.cleaned_data['new_password']
            if request.user.check_password(old_password):
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user)
                return redirect('users:profile')
            else:
                forms.add_error('old_password', 'Incorrect old password')

    else:
        form = ProfileForm(instance=request.user)
        forms = ResetPasswordForm()

    return render(request, 'users/edit-profile.html',{"form":form, 'forms':forms})

users/templates/users/edit-profile.html
{% extends 'base.html' %}

{% block content %}
	<div class="card">
        {% if user.image %}
      	<img src="{{ user.image.url }}" alt="John" style="width:300px; height: 300px; border-radius: 50%">
      {% else %}
          <img src="https://t3.ftcdn.net/jpg/05/53/79/60/360_F_553796090_XHrE6R9jwmBJUMo9HKl41hyHJ5gqt9oz.jpg" alt="John" style="width:300px; height: 300px; border-radius: 50%">
      {% endif %}
      <div class="profile">
          <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                {{ form }}
              <a id="reset_password">Parolni yangilash</a>
            <button type="submit">Saqlash</button>
        </form>
      </div>
    </div>

    <div class="modal" id="reset">
      <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Parolni yangilash</h2>
        <form action="#" method="POST">
            {% csrf_token %}
            {{ forms }}
            <button type="submit">Tasdiqlash</button>
        </form>
      </div>
    </div>

    <script>
        var loginModal = document.getElementById("reset");
        var loginBtn = document.getElementById("reset_password");
        var loginClose = loginModal.getElementsByClassName("close")[0];

        loginBtn.addEventListener('click', (e)=>{
            e.preventDefault()
            loginModal.style.display = "block";
            registerModal.style.display = "none";
        })

        loginClose.addEventListener('click', (e)=>{
            e.preventDefault()
            loginModal.style.display = "none";
        })

        var login = document.getElementById("reset_password");

        login.addEventListener('click', (e)=>{
            e.preventDefault()
            loginModal.style.display = "block";
            registerModal.style.display = "none";
        })
    </script>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
      {% if user.image %}
      	<img src="{{ user.image.url }}" alt="John" style="width:300px; height: 300px; border-radius: 50%">
      {% else %}
          <img src="https://t3.ftcdn.net/jpg/05/53/79/60/360_F_553796090_XHrE6R9jwmBJUMo9HKl41hyHJ5gqt9oz.jpg" alt="John" style="width:300px; height: 300px; border-radius: 50%">
      {% endif %}
      <div class="profile">
          <h1>{{ user.username }}</h1>
          <p class="title">Ismi: {{ user.first_name }}</p>
          <p class="title">Familiyasi: {{ user.last_name }}</p>
          <p class="title">Email: {{ user.email }}</p>
          <p>Qo'shilgan: {{ user.date_joined|date }}</p>
          <p>
              <a href="{% url 'users:edit_profile' %}" class="btn-edit">Tahrirlash</a>
              <a href="{% url 'users:logout' %}" class="btn-edit">Logout</a>
          </p>
      </div>
    </div>
{% endblock %}