books/urls.py
from django.urls import path
from .views import CategoryView, BookDetail,AddCommentView,about,books,GenresView

app_name = 'books'
urlpatterns = [
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('genre/<int:genre_id>/', GenresView.as_view(), name='genres'),
    path('detail/<int:pk>/', BookDetail.as_view(), name='detail'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='add_comment'),
    path('about/', about, name='about'),
    path('books/', books, name='books'),
]

mybooks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    image = models.ImageField(upload_to='books/', blank=True, null=True)
    year = models.IntegerField()
    about = models.TextField()
    piece_of_the_book = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='books')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='books')

    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    given_stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.user} rated to {self.book} stars given {self.given_stars}"

class SiteDesign(models.Model):
    image = models.ImageField(upload_to='site/', blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField()

books/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class':'commenttext','rows':5}))
    given_stars = forms.IntegerField(min_value=1,max_value=5,widget=forms.NumberInput(attrs={'class':'given'}))
    class Meta:
        model = Comment
        fields = ['comment', 'given_stars']

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View

from books.forms import CommentForm
from books.models import Category, Book, Comment,SiteDesign,Genre


class CategoryView(View):
    def get(self,request,category_id):
        category = Category.objects.get(id=category_id)
        books = category.books.all()

        ratings = {}
        regular_ratings = {}
        for book in books:
            rating = 0
            for book_comment in book.comments.all():
                rating += book_comment.given_stars
            try:
                avg_rating = round(rating / len(book.comments.all()))
            except ZeroDivisionError:
                avg_rating = 0
            ratings[book.id] = avg_rating
            regular_ratings[book.id] = 5 - avg_rating

        data = {
            "books": books,
            "category":category,
            "ratings":ratings,
            "regular_ratings":regular_ratings,
        }
        return render(request, 'books/category.html', context=data)

class BookDetail(View):

    def get(self,request,pk):
        comments = Comment.objects.filter(book_id=pk).order_by("-id")
        books = Book.objects.all()
        book = Book.objects.get(id=pk)
        form = CommentForm()

        comment_regular_ratings = {}
        for comment in comments:
            comment_regular_ratings[comment.id] = 5-comment.given_stars

        ratings = {}
        regular_ratings = {}
        for b in books:
            rating = 0
            for book_comment in book.comments.all():
                rating += book_comment.given_stars
            try:
                avg_rating = round(rating / len(book.comments.all()))
            except ZeroDivisionError:
                avg_rating = 0
            ratings[b.id] = avg_rating
            regular_ratings[b.id] = 5 - avg_rating

        data = {
            'book': book,
            'form_comment': form,
            'comments': comments,
            'ratings': ratings,
            'regular_ratings':regular_ratings,
            'regular_book_rate': comment_regular_ratings
        }
        return render(request, 'books/detail.html', context=data)

class AddCommentView(View):
    def post(self,request,pk):
        form = CommentForm(request.POST)
        book = Book.objects.get(id=pk)
        if form.is_valid():
            Comment.objects.create(
                user = request.user,
                book = book,
                comment = form.cleaned_data['comment'],
                given_stars = form.cleaned_data['given_stars']
            )
            return redirect(reverse('books:detail', kwargs={'pk': book.id}))
        return render(request, 'books/detail.html', {'book':book,'form_comment':form})

def about(request):
    site = SiteDesign.objects.first()
    return render(request, 'books/about.html', context={'site':site})

def books(request):
    books = Book.objects.all()

    ratings = {}
    regular_ratings = {}
    for book in books:
        rating = 0
        for book_comment in book.comments.all():
            rating += book_comment.given_stars
        try:
            avg_rating = round(rating / len(book.comments.all()))
        except ZeroDivisionError:
            avg_rating = 0
        ratings[book.id] = avg_rating
        regular_ratings[book.id] = 5 - avg_rating

    data = {
        "books": books,
        "ratings": ratings,
        "regular_ratings": regular_ratings,
    }
    return render(request, 'books/books.html', context=data)

class GenresView(View):
    def get(self,request,genre_id):
        genre = Genre.objects.get(id=genre_id)
        books = genre.books.all()

        ratings = {}
        regular_ratings = {}
        for book in books:
            rating = 0
            for book_comment in book.comments.all():
                rating += book_comment.given_stars
            try:
                avg_rating = round(rating / len(book.comments.all()))
            except ZeroDivisionError:
                avg_rating = 0
            ratings[book.id] = avg_rating
            regular_ratings[book.id] = 5 - avg_rating

        data = {
            "books": books,
            "genre":genre,
            "ratings":ratings,
            "regular_ratings":regular_ratings,
        }
        return render(request, 'books/genres.html', context=data)

books/templates/books/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="">
        <img src="{{ site.image.url }}" alt="John" width="100%">
      <div class="profile">
          <h1>{{ site.title }}</h1>
          <p class="title"></p>
                {{ site.description }}
          <p>
              <a href="{% url 'index' %}" class="btn-edit">Bookinfo.uz</a>
          </p>
      </div>
    </div>
{% endblock %}

books/templates/books/books.html
{% extends 'base.html' %}

{% block content %}
	<section class="">
            {% for book in books %}
            	<div class="post">
            <!-- post-inner -->
            <div class="post-inner">
              <header>
                <h2><a href="#">{{ book.name }}</a></h2>
                <p class="tags"><a href="#">{{ book.category.name }}</a> <a href="#">{{ book.genre.name }}</a> </p>
                <div class="cl">&nbsp;</div>
              </header>
              <div class="img-holder"> <a href="#"><img src="{{ book.image.url }}" alt="" width="100%"></a> <a href="{{ book.image.url }}" class="btn-full-image popup"><span>FULL IMAGE</span></a> </div>
              <!-- meta -->
              <div class="meta">
                <p class="date">{{ book.year }} by <a>{{ book.author }}</a></p>
                <div class="right">
                  <div class="rating-holder">
                    <p>REYTING</p>&nbsp;
                    {% for key,value in ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-solid fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                        {% for key,value in regular_ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in "x"|ljust:value %}
                                           <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                  </div>
                  <a href="{% url 'books:detail' book.id %}" class="comments">{{ book.comments.count }} ta izoh</a> </div>
                <div class="cl">&nbsp;</div>
              </div>
              <!-- end of meta -->
              <!-- post-cnt -->
              <div class="post-cnt">
                <p>{{ book.about|truncatewords:60|linebreaks }}</p>
                <a href="{% url 'books:detail' book.id %}" class="more">Batafsil o'qish</a> </div>
              <!-- end of post-cnt -->
            </div>
            <!-- post-inner -->
          </div>
            {% endfor %}

        </section>

        <div class="modal" id="myModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Ro'yxatdan o'tish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ forms }}
        <span>Allaqachon hisobingiz bormi? <span id="login" class="signup">Kirish</span></span>
      <button type="submit">Ro'yxatdan o'tish</button>
    </form>
  </div>
</div>
<div class="modal" id="loginModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Kirish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <span>Akkountingiz yo'qmi? <span id="myBtn" class="signup">Ro'yxatdan o'tish</span></span>
        <button type="submit">Kirish</button>
    </form>
  </div>
</div>

<script>
// Modalni ochish va yopish
var registerModal = document.getElementById("myModal");
var registerBtn = document.getElementById("myBtn");
var registerClose = registerModal.getElementsByClassName("close")[0];

registerBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "block";
    loginModal.style.display = "none";
})


registerClose.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "none";
})

var loginModal = document.getElementById("loginModal");
var loginBtn = document.getElementById("loginBtn");
var loginClose = loginModal.getElementsByClassName("close")[0];

loginBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})

loginClose.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "none";
})

var login = document.getElementById("login");

login.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})


</script>
{% endblock %}

books/templates/books/category.html
{% extends 'base.html' %}

{% block content %}
	<section class="">
            {% for book in books %}
            	<div class="post">
            <!-- post-inner -->
            <div class="post-inner">
              <header>
                <h2><a href="#">{{ book.name }}</a></h2>
                <p class="tags"><a href="#">{{ book.category.name }}</a> <a href="#">{{ book.genre.name }}</a> </p>
                <div class="cl">&nbsp;</div>
              </header>
              <div class="img-holder"> <a href="#"><img src="{{ book.image.url }}" alt="" width="100%"></a> <a href="{{ book.image.url }}" class="btn-full-image popup"><span>FULL IMAGE</span></a> </div>
              <!-- meta -->
              <div class="meta">
                <p class="date">{{ book.year }} by <a>{{ book.author }}</a></p>
                <div class="right">
                  <div class="rating-holder">
                    <p>REYTING</p>&nbsp;
                    {% for key,value in ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-solid fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                        {% for key,value in regular_ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                  </div>
                  <a href="{% url 'books:detail' book.id %}" class="comments">{{ book.comments.count }} ta izoh</a> </div>
                <div class="cl">&nbsp;</div>
              </div>
              <!-- end of meta -->
              <!-- post-cnt -->
              <div class="post-cnt">
                <p>{{ book.about|truncatewords:60|linebreaks }}</p>
                <a href="{% url 'books:detail' book.id %}" class="more">Batafsil o'qish</a> </div>
              <!-- end of post-cnt -->
            </div>
            <!-- post-inner -->
          </div>
            {% endfor %}

        </section>

        <div class="modal" id="myModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Ro'yxatdan o'tish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ forms }}
        <span>Allaqachon hisobingiz bormi? <span id="login" class="signup">Kirish</span></span>
      <button type="submit">Ro'yxatdan o'tish</button>
    </form>
  </div>
</div>
<div class="modal" id="loginModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Kirish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <span>Akkountingiz yo'qmi? <span id="myBtn" class="signup">Ro'yxatdan o'tish</span></span>
        <button type="submit">Kirish</button>
    </form>
  </div>
</div>

<script>
// Modalni ochish va yopish
var registerModal = document.getElementById("myModal");
var registerBtn = document.getElementById("myBtn");
var registerClose = registerModal.getElementsByClassName("close")[0];

registerBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "block";
    loginModal.style.display = "none";
})


registerClose.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "none";
})

var loginModal = document.getElementById("loginModal");
var loginBtn = document.getElementById("loginBtn");
var loginClose = loginModal.getElementsByClassName("close")[0];

loginBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})

loginClose.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "none";
})

var login = document.getElementById("login");

login.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})


</script>
{% endblock %}

books/templates/books/detail.html
{% extends 'base.html' %}

{% block content %}
	 <section class="content">
          <div class="post">
            <!-- post-inner -->
            <div class="post-inner">
              <header>
                <h2><a href="#">{{ book.name }}</a></h2>
                <p class="tags"><a href="#">{{ book.category.name }}</a> <a href="#">{{ book.genre.name }}</a> </p>
                <div class="cl">&nbsp;</div>
              </header>
              <div class="img-holder"> <a href="#"><img src="{{ book.image.url }}" alt="" width="100%"></a> <a href="{{ book.image.url }}" class="btn-full-image popup"><span>FULL IMAGE</span></a> </div>
              <!-- meta -->
              <div class="meta">
                <p class="date">{{ book.year }} by <a>{{ book.author }}</a></p>
                <div class="right">
                  <div class="rating-holder">
                    <p><REYTING></REYTING></p>&nbsp;
                    {% for key,value in ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-solid fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                        {% for key,value in regular_ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}

                  </div>
                  <a class="comments">{{ book.comments.count }} ta izoh</a> </div>
                <div class="cl">&nbsp;</div>
              </div>
              <!-- end of meta -->
              <!-- post-cnt -->
              <div class="post-cnt">
                <p>{{ book.piece_of_the_book }}</p>
              <!-- end of post-cnt -->
              </div>
            <!-- post-inner -->
          </div>
          </div>
        </section>
        <!-- end of content -->
        <!-- sidebar -->
        <aside class="sidebar">
          <div class="widget">
            <h3 class="widgettitle">Kitob haqida</h3>
            <ul>
                 <li><a>Nomi: {{ book.name }}</a></li>
                 <li><a>Muallifi: {{ book.author }}</a></li>
                 <li><a>Davlati: {{ book.country }}</a></li>
                 <li><a>Year: {{ book.year }}</a></li>
                 <li><a>Category: {{ book.category }}</a></li>
                 <li><a>Janri: {{ book.genre }}</a></li>
            </ul>
          </div>
        </aside>
    <aside class="sidebar">
          <div class="widget">
            <h3 class="widgettitle">Izoh qoldirish</h3>
              <div class="modal-content">
                  <form action="{% url 'books:add_comment' book.id %}" method="POST" class="commentform">
                  {% csrf_token %}
                  {{ form_comment }}
                  {% if user.is_authenticated %}
                  	<button type="submit">Qoldirish</button>
                  {% else %}
                      <a href="{% url 'index' %}"><button class="commentbtn" type="button">Qoldirish</button></a>
                  {% endif %}
              </form>
              </div>
          </div>
        </aside>

    <aside class="sidebar">
          <div class="widget">
            <h3 class="widgettitle">Izohlar</h3>

                {% for comment in comments %}
                    <div class="container">
                	<div class="comment">
                        <div class="user-info">
                            {% if comment.user.image %}
                            	<img src="{{ comment.user.image.url }}" alt="User Avatar">
                            {% else %}
                                <img src="https://t3.ftcdn.net/jpg/05/53/79/60/360_F_553796090_XHrE6R9jwmBJUMo9HKl41hyHJ5gqt9oz.jpg" alt="User Avatar">
                            {% endif %}
                            <p class="username">{{ comment.user.username }}</p>
                        </div>
                        <div class="rating-holder">
                            {% for foo in ""|ljust:comment.given_stars %}
                                <i class="fa-solid fa-star"></i>
                            {% endfor %}

                            {% for key,value in regular_book_rate.items %}
                            	{% if key == comment.id %}
                            		{% for foo in ""|ljust:value %}
                                        <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                            	{% endif %}
                            {% endfor %}
                        </div>
                        <p class="comment-text">{{ comment.comment }}</p>
                    </div>
                </div>
                {% endfor %}

          </div>
        </aside>

    <div class="modal" id="myModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Ro'yxatdan o'tish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ forms }}
        <span>Allaqachon hisobingiz bormi? <span id="login" class="signup">Kirish</span></span>
      <button type="submit">Ro'yxatdan o'tish</button>
    </form>
  </div>
</div>
<div class="modal" id="loginModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Kirish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <span>Akkountingiz yo'qmi? <span id="myBtn" class="signup">Ro'yxatdan o'tish</span></span>
        <button type="submit">Kirish</button>
    </form>
  </div>
</div>

<script>
// Modalni ochish va yopish
var registerModal = document.getElementById("myModal");
var registerBtn = document.getElementById("myBtn");
var registerClose = registerModal.getElementsByClassName("close")[0];

registerBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "block";
    loginModal.style.display = "none";
})


registerClose.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "none";
})

var loginModal = document.getElementById("loginModal");
var loginBtn = document.getElementById("loginBtn");
var loginClose = loginModal.getElementsByClassName("close")[0];

loginBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})

loginClose.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "none";
})

var login = document.getElementById("login");

login.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})


</script>
{% endblock %}

books/templates/books/genres.html
{% extends 'base.html' %}

{% block content %}
	<section class="">
            {% for book in books %}
            	<div class="post">
            <!-- post-inner -->
            <div class="post-inner">
              <header>
                <h2><a href="#">{{ book.name }}</a></h2>
                <p class="tags"><a href="#">{{ book.category.name }}</a> <a href="#">{{ book.genre.name }}</a> </p>
                <div class="cl">&nbsp;</div>
              </header>
              <div class="img-holder"> <a href="#"><img src="{{ book.image.url }}" alt="" width="100%"></a> <a href="{{ book.image.url }}" class="btn-full-image popup"><span>FULL IMAGE</span></a> </div>
              <!-- meta -->
              <div class="meta">
                <p class="date">{{ book.year }} by <a>{{ book.author }}</a></p>
                <div class="right">
                  <div class="rating-holder">
                    <p>REYTING</p>&nbsp;
                    {% for key,value in ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-solid fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                        {% for key,value in regular_ratings.items %}
                        	{% if key == book.id %}
                        		    {% for foo in ""|ljust:value %}
                                           <i class="fa-regular fa-star"></i>
                                    {% endfor %}
                        	{% endif %}
                        {% endfor %}
                  </div>
                  <a href="{% url 'books:detail' book.id %}" class="comments">{{ book.comments.count }} ta izoh</a> </div>
                <div class="cl">&nbsp;</div>
              </div>
              <!-- end of meta -->
              <!-- post-cnt -->
              <div class="post-cnt">
                <p>{{ book.about|truncatewords:60|linebreaks }}</p>
                <a href="{% url 'books:detail' book.id %}" class="more">Batafsil o'qish</a> </div>
              <!-- end of post-cnt -->
            </div>
            <!-- post-inner -->
          </div>
            {% endfor %}

        </section>

        <div class="modal" id="myModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Ro'yxatdan o'tish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ forms }}
        <span>Allaqachon hisobingiz bormi? <span id="login" class="signup">Kirish</span></span>
      <button type="submit">Ro'yxatdan o'tish</button>
    </form>
  </div>
</div>
<div class="modal" id="loginModal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Kirish</h2>
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <span>Akkountingiz yo'qmi? <span id="myBtn" class="signup">Ro'yxatdan o'tish</span></span>
        <button type="submit">Kirish</button>
    </form>
  </div>
</div>

<script>
// Modalni ochish va yopish
var registerModal = document.getElementById("myModal");
var registerBtn = document.getElementById("myBtn");
var registerClose = registerModal.getElementsByClassName("close")[0];

registerBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "block";
    loginModal.style.display = "none";
})


registerClose.addEventListener('click', (e)=>{
    e.preventDefault()
    registerModal.style.display = "none";
})

var loginModal = document.getElementById("loginModal");
var loginBtn = document.getElementById("loginBtn");
var loginClose = loginModal.getElementsByClassName("close")[0];

loginBtn.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})

loginClose.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "none";
})

var login = document.getElementById("login");

login.addEventListener('click', (e)=>{
    e.preventDefault()
    loginModal.style.display = "block";
    registerModal.style.display = "none";
})


</script>
{% endblock %}